name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sh compile_executable.sh
    - name: run executable
      run: ./app.exe

      run: make check
    - name: make distcheck
      run: make distcheck
